/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BulkemailsenderRouteRouteImport } from './routes/bulkemailsender/route'
import { Route as BulkemailsenderUnlockRouteImport } from './routes/bulkemailsender-unlock'
import { Route as BulkemailsenderAuthenticatedRouteRouteImport } from './routes/bulkemailsender/_authenticated/route'
import { Route as BulkemailsenderAuthRouteImport } from './routes/bulkemailsender/auth'
import { Route as BulkemailsenderAuthenticatedIndexRouteImport } from './routes/bulkemailsender/_authenticated/index'
import { Route as BulkemailsenderAuthenticatedAccountsRouteImport } from './routes/bulkemailsender/_authenticated/accounts'
import { Route as BulkemailsenderAuthenticatedActivityRouteImport } from './routes/bulkemailsender/_authenticated/activity'
import { Route as BulkemailsenderAuthenticatedAnalyticsRouteImport } from './routes/bulkemailsender/_authenticated/analytics'
import { Route as BulkemailsenderAuthenticatedFollowUpsRouteImport } from './routes/bulkemailsender/_authenticated/follow-ups'
import { Route as BulkemailsenderAuthenticatedImportRouteImport } from './routes/bulkemailsender/_authenticated/import'
import { Route as BulkemailsenderAuthenticatedSettingsRouteImport } from './routes/bulkemailsender/_authenticated/settings'
import { Route as BulkemailsenderAuthenticatedTemplatesRouteImport } from './routes/bulkemailsender/_authenticated/templates'
import { Route as ApiPublicOpenRecipientIdRouteImport } from './routes/api/public/open.$recipientId'
import { Route as BulkemailsenderAuthenticatedCampaignsIndexRouteImport } from './routes/bulkemailsender/_authenticated/campaigns.index'
import { Route as BulkemailsenderAuthenticatedCampaignsCampaignIdRouteImport } from './routes/bulkemailsender/_authenticated/campaigns.$campaignId'
import { Route as BulkemailsenderAuthenticatedCampaignsNewRouteImport } from './routes/bulkemailsender/_authenticated/campaigns.new'
import { Route as BulkemailsenderAuthenticatedProspectsIndexRouteImport } from './routes/bulkemailsender/_authenticated/prospects.index'
import { Route as BulkemailsenderAuthenticatedProspectsProspectIdRouteImport } from './routes/bulkemailsender/_authenticated/prospects.$prospectId'
import { Route as BulkemailsenderOauthGoogleMailReturnRouteImport } from './routes/bulkemailsender/oauth/google-mail/return'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkemailsenderRouteRoute = BulkemailsenderRouteRouteImport.update({
  id: '/bulkemailsender',
  path: '/bulkemailsender',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkemailsenderUnlockRoute = BulkemailsenderUnlockRouteImport.update({
  id: '/bulkemailsender-unlock',
  path: '/bulkemailsender-unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkemailsenderAuthenticatedRouteRoute =
  BulkemailsenderAuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => BulkemailsenderRouteRoute,
  } as any)
const BulkemailsenderAuthRoute = BulkemailsenderAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => BulkemailsenderRouteRoute,
} as any)
const BulkemailsenderAuthenticatedIndexRoute =
  BulkemailsenderAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BulkemailsenderAuthenticatedRouteRoute,
  } as any)
const BulkemailsenderAuthenticatedAccountsRoute =
  BulkemailsenderAuthenticatedAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => BulkemailsenderAuthenticatedRouteRoute,
  } as any)
const BulkemailsenderAuthenticatedActivityRoute =
  BulkemailsenderAuthenticatedActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => BulkemailsenderAuthenticatedRouteRoute,
  } as any)
const BulkemailsenderAuthenticatedAnalyticsRoute =
  BulkemailsenderAuthenticatedAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => BulkemailsenderAuthenticatedRouteRoute,
  } as any)
const BulkemailsenderAuthenticatedFollowUpsRoute =
  BulkemailsenderAuthenticatedFollowUpsRouteImport.update({
    id: '/follow-ups',
    path: '/follow-ups',
    getParentRoute: () => BulkemailsenderAuthenticatedRouteRoute,
  } as any)
const BulkemailsenderAuthenticatedImportRoute =
  BulkemailsenderAuthenticatedImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => BulkemailsenderAuthenticatedRouteRoute,
  } as any)
const BulkemailsenderAuthenticatedSettingsRoute =
  BulkemailsenderAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => BulkemailsenderAuthenticatedRouteRoute,
  } as any)
const BulkemailsenderAuthenticatedTemplatesRoute =
  BulkemailsenderAuthenticatedTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => BulkemailsenderAuthenticatedRouteRoute,
  } as any)
const ApiPublicOpenRecipientIdRoute =
  ApiPublicOpenRecipientIdRouteImport.update({
    id: '/api/public/open/$recipientId',
    path: '/api/public/open/$recipientId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BulkemailsenderAuthenticatedCampaignsIndexRoute =
  BulkemailsenderAuthenticatedCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => BulkemailsenderAuthenticatedRouteRoute,
  } as any)
const BulkemailsenderAuthenticatedCampaignsCampaignIdRoute =
  BulkemailsenderAuthenticatedCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => BulkemailsenderAuthenticatedRouteRoute,
  } as any)
const BulkemailsenderAuthenticatedCampaignsNewRoute =
  BulkemailsenderAuthenticatedCampaignsNewRouteImport.update({
    id: '/campaigns/new',
    path: '/campaigns/new',
    getParentRoute: () => BulkemailsenderAuthenticatedRouteRoute,
  } as any)
const BulkemailsenderAuthenticatedProspectsIndexRoute =
  BulkemailsenderAuthenticatedProspectsIndexRouteImport.update({
    id: '/prospects/',
    path: '/prospects/',
    getParentRoute: () => BulkemailsenderAuthenticatedRouteRoute,
  } as any)
const BulkemailsenderAuthenticatedProspectsProspectIdRoute =
  BulkemailsenderAuthenticatedProspectsProspectIdRouteImport.update({
    id: '/prospects/$prospectId',
    path: '/prospects/$prospectId',
    getParentRoute: () => BulkemailsenderAuthenticatedRouteRoute,
  } as any)
const BulkemailsenderOauthGoogleMailReturnRoute =
  BulkemailsenderOauthGoogleMailReturnRouteImport.update({
    id: '/oauth/google-mail/return',
    path: '/oauth/google-mail/return',
    getParentRoute: () => BulkemailsenderRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bulkemailsender': typeof BulkemailsenderRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/bulkemailsender-unlock': typeof BulkemailsenderUnlockRoute
  '/bulkemailsender/auth': typeof BulkemailsenderAuthRoute
  '/bulkemailsender/accounts': typeof BulkemailsenderAuthenticatedAccountsRoute
  '/bulkemailsender/activity': typeof BulkemailsenderAuthenticatedActivityRoute
  '/bulkemailsender/analytics': typeof BulkemailsenderAuthenticatedAnalyticsRoute
  '/bulkemailsender/follow-ups': typeof BulkemailsenderAuthenticatedFollowUpsRoute
  '/bulkemailsender/import': typeof BulkemailsenderAuthenticatedImportRoute
  '/bulkemailsender/settings': typeof BulkemailsenderAuthenticatedSettingsRoute
  '/bulkemailsender/templates': typeof BulkemailsenderAuthenticatedTemplatesRoute
  '/bulkemailsender/': typeof BulkemailsenderAuthenticatedIndexRoute
  '/api/public/open/$recipientId': typeof ApiPublicOpenRecipientIdRoute
  '/bulkemailsender/campaigns/$campaignId': typeof BulkemailsenderAuthenticatedCampaignsCampaignIdRoute
  '/bulkemailsender/campaigns/new': typeof BulkemailsenderAuthenticatedCampaignsNewRoute
  '/bulkemailsender/prospects/$prospectId': typeof BulkemailsenderAuthenticatedProspectsProspectIdRoute
  '/bulkemailsender/oauth/google-mail/return': typeof BulkemailsenderOauthGoogleMailReturnRoute
  '/bulkemailsender/campaigns/': typeof BulkemailsenderAuthenticatedCampaignsIndexRoute
  '/bulkemailsender/prospects/': typeof BulkemailsenderAuthenticatedProspectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bulkemailsender': typeof BulkemailsenderAuthenticatedIndexRoute
  '/$': typeof SplatRoute
  '/bulkemailsender-unlock': typeof BulkemailsenderUnlockRoute
  '/bulkemailsender/auth': typeof BulkemailsenderAuthRoute
  '/bulkemailsender/accounts': typeof BulkemailsenderAuthenticatedAccountsRoute
  '/bulkemailsender/activity': typeof BulkemailsenderAuthenticatedActivityRoute
  '/bulkemailsender/analytics': typeof BulkemailsenderAuthenticatedAnalyticsRoute
  '/bulkemailsender/follow-ups': typeof BulkemailsenderAuthenticatedFollowUpsRoute
  '/bulkemailsender/import': typeof BulkemailsenderAuthenticatedImportRoute
  '/bulkemailsender/settings': typeof BulkemailsenderAuthenticatedSettingsRoute
  '/bulkemailsender/templates': typeof BulkemailsenderAuthenticatedTemplatesRoute
  '/api/public/open/$recipientId': typeof ApiPublicOpenRecipientIdRoute
  '/bulkemailsender/campaigns/$campaignId': typeof BulkemailsenderAuthenticatedCampaignsCampaignIdRoute
  '/bulkemailsender/campaigns/new': typeof BulkemailsenderAuthenticatedCampaignsNewRoute
  '/bulkemailsender/prospects/$prospectId': typeof BulkemailsenderAuthenticatedProspectsProspectIdRoute
  '/bulkemailsender/oauth/google-mail/return': typeof BulkemailsenderOauthGoogleMailReturnRoute
  '/bulkemailsender/campaigns': typeof BulkemailsenderAuthenticatedCampaignsIndexRoute
  '/bulkemailsender/prospects': typeof BulkemailsenderAuthenticatedProspectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bulkemailsender': typeof BulkemailsenderRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/bulkemailsender-unlock': typeof BulkemailsenderUnlockRoute
  '/bulkemailsender/_authenticated': typeof BulkemailsenderAuthenticatedRouteRouteWithChildren
  '/bulkemailsender/auth': typeof BulkemailsenderAuthRoute
  '/bulkemailsender/_authenticated/accounts': typeof BulkemailsenderAuthenticatedAccountsRoute
  '/bulkemailsender/_authenticated/activity': typeof BulkemailsenderAuthenticatedActivityRoute
  '/bulkemailsender/_authenticated/analytics': typeof BulkemailsenderAuthenticatedAnalyticsRoute
  '/bulkemailsender/_authenticated/follow-ups': typeof BulkemailsenderAuthenticatedFollowUpsRoute
  '/bulkemailsender/_authenticated/import': typeof BulkemailsenderAuthenticatedImportRoute
  '/bulkemailsender/_authenticated/settings': typeof BulkemailsenderAuthenticatedSettingsRoute
  '/bulkemailsender/_authenticated/templates': typeof BulkemailsenderAuthenticatedTemplatesRoute
  '/bulkemailsender/_authenticated/': typeof BulkemailsenderAuthenticatedIndexRoute
  '/api/public/open/$recipientId': typeof ApiPublicOpenRecipientIdRoute
  '/bulkemailsender/_authenticated/campaigns/$campaignId': typeof BulkemailsenderAuthenticatedCampaignsCampaignIdRoute
  '/bulkemailsender/_authenticated/campaigns/new': typeof BulkemailsenderAuthenticatedCampaignsNewRoute
  '/bulkemailsender/_authenticated/prospects/$prospectId': typeof BulkemailsenderAuthenticatedProspectsProspectIdRoute
  '/bulkemailsender/oauth/google-mail/return': typeof BulkemailsenderOauthGoogleMailReturnRoute
  '/bulkemailsender/_authenticated/campaigns/': typeof BulkemailsenderAuthenticatedCampaignsIndexRoute
  '/bulkemailsender/_authenticated/prospects/': typeof BulkemailsenderAuthenticatedProspectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bulkemailsender'
    | '/$'
    | '/bulkemailsender-unlock'
    | '/bulkemailsender/auth'
    | '/bulkemailsender/accounts'
    | '/bulkemailsender/activity'
    | '/bulkemailsender/analytics'
    | '/bulkemailsender/follow-ups'
    | '/bulkemailsender/import'
    | '/bulkemailsender/settings'
    | '/bulkemailsender/templates'
    | '/bulkemailsender/'
    | '/api/public/open/$recipientId'
    | '/bulkemailsender/campaigns/$campaignId'
    | '/bulkemailsender/campaigns/new'
    | '/bulkemailsender/prospects/$prospectId'
    | '/bulkemailsender/oauth/google-mail/return'
    | '/bulkemailsender/campaigns/'
    | '/bulkemailsender/prospects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bulkemailsender'
    | '/$'
    | '/bulkemailsender-unlock'
    | '/bulkemailsender/auth'
    | '/bulkemailsender/accounts'
    | '/bulkemailsender/activity'
    | '/bulkemailsender/analytics'
    | '/bulkemailsender/follow-ups'
    | '/bulkemailsender/import'
    | '/bulkemailsender/settings'
    | '/bulkemailsender/templates'
    | '/api/public/open/$recipientId'
    | '/bulkemailsender/campaigns/$campaignId'
    | '/bulkemailsender/campaigns/new'
    | '/bulkemailsender/prospects/$prospectId'
    | '/bulkemailsender/oauth/google-mail/return'
    | '/bulkemailsender/campaigns'
    | '/bulkemailsender/prospects'
  id:
    | '__root__'
    | '/'
    | '/bulkemailsender'
    | '/$'
    | '/bulkemailsender-unlock'
    | '/bulkemailsender/_authenticated'
    | '/bulkemailsender/auth'
    | '/bulkemailsender/_authenticated/accounts'
    | '/bulkemailsender/_authenticated/activity'
    | '/bulkemailsender/_authenticated/analytics'
    | '/bulkemailsender/_authenticated/follow-ups'
    | '/bulkemailsender/_authenticated/import'
    | '/bulkemailsender/_authenticated/settings'
    | '/bulkemailsender/_authenticated/templates'
    | '/bulkemailsender/_authenticated/'
    | '/api/public/open/$recipientId'
    | '/bulkemailsender/_authenticated/campaigns/$campaignId'
    | '/bulkemailsender/_authenticated/campaigns/new'
    | '/bulkemailsender/_authenticated/prospects/$prospectId'
    | '/bulkemailsender/oauth/google-mail/return'
    | '/bulkemailsender/_authenticated/campaigns/'
    | '/bulkemailsender/_authenticated/prospects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BulkemailsenderRouteRoute: typeof BulkemailsenderRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  BulkemailsenderUnlockRoute: typeof BulkemailsenderUnlockRoute
  ApiPublicOpenRecipientIdRoute: typeof ApiPublicOpenRecipientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulkemailsender': {
      id: '/bulkemailsender'
      path: '/bulkemailsender'
      fullPath: '/bulkemailsender'
      preLoaderRoute: typeof BulkemailsenderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulkemailsender-unlock': {
      id: '/bulkemailsender-unlock'
      path: '/bulkemailsender-unlock'
      fullPath: '/bulkemailsender-unlock'
      preLoaderRoute: typeof BulkemailsenderUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulkemailsender/_authenticated': {
      id: '/bulkemailsender/_authenticated'
      path: ''
      fullPath: '/bulkemailsender'
      preLoaderRoute: typeof BulkemailsenderAuthenticatedRouteRouteImport
      parentRoute: typeof BulkemailsenderRouteRoute
    }
    '/bulkemailsender/auth': {
      id: '/bulkemailsender/auth'
      path: '/auth'
      fullPath: '/bulkemailsender/auth'
      preLoaderRoute: typeof BulkemailsenderAuthRouteImport
      parentRoute: typeof BulkemailsenderRouteRoute
    }
    '/bulkemailsender/_authenticated/': {
      id: '/bulkemailsender/_authenticated/'
      path: '/'
      fullPath: '/bulkemailsender/'
      preLoaderRoute: typeof BulkemailsenderAuthenticatedIndexRouteImport
      parentRoute: typeof BulkemailsenderAuthenticatedRouteRoute
    }
    '/bulkemailsender/_authenticated/accounts': {
      id: '/bulkemailsender/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/bulkemailsender/accounts'
      preLoaderRoute: typeof BulkemailsenderAuthenticatedAccountsRouteImport
      parentRoute: typeof BulkemailsenderAuthenticatedRouteRoute
    }
    '/bulkemailsender/_authenticated/activity': {
      id: '/bulkemailsender/_authenticated/activity'
      path: '/activity'
      fullPath: '/bulkemailsender/activity'
      preLoaderRoute: typeof BulkemailsenderAuthenticatedActivityRouteImport
      parentRoute: typeof BulkemailsenderAuthenticatedRouteRoute
    }
    '/bulkemailsender/_authenticated/analytics': {
      id: '/bulkemailsender/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/bulkemailsender/analytics'
      preLoaderRoute: typeof BulkemailsenderAuthenticatedAnalyticsRouteImport
      parentRoute: typeof BulkemailsenderAuthenticatedRouteRoute
    }
    '/bulkemailsender/_authenticated/follow-ups': {
      id: '/bulkemailsender/_authenticated/follow-ups'
      path: '/follow-ups'
      fullPath: '/bulkemailsender/follow-ups'
      preLoaderRoute: typeof BulkemailsenderAuthenticatedFollowUpsRouteImport
      parentRoute: typeof BulkemailsenderAuthenticatedRouteRoute
    }
    '/bulkemailsender/_authenticated/import': {
      id: '/bulkemailsender/_authenticated/import'
      path: '/import'
      fullPath: '/bulkemailsender/import'
      preLoaderRoute: typeof BulkemailsenderAuthenticatedImportRouteImport
      parentRoute: typeof BulkemailsenderAuthenticatedRouteRoute
    }
    '/bulkemailsender/_authenticated/settings': {
      id: '/bulkemailsender/_authenticated/settings'
      path: '/settings'
      fullPath: '/bulkemailsender/settings'
      preLoaderRoute: typeof BulkemailsenderAuthenticatedSettingsRouteImport
      parentRoute: typeof BulkemailsenderAuthenticatedRouteRoute
    }
    '/bulkemailsender/_authenticated/templates': {
      id: '/bulkemailsender/_authenticated/templates'
      path: '/templates'
      fullPath: '/bulkemailsender/templates'
      preLoaderRoute: typeof BulkemailsenderAuthenticatedTemplatesRouteImport
      parentRoute: typeof BulkemailsenderAuthenticatedRouteRoute
    }
    '/api/public/open/$recipientId': {
      id: '/api/public/open/$recipientId'
      path: '/api/public/open/$recipientId'
      fullPath: '/api/public/open/$recipientId'
      preLoaderRoute: typeof ApiPublicOpenRecipientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulkemailsender/_authenticated/campaigns/': {
      id: '/bulkemailsender/_authenticated/campaigns/'
      path: '/campaigns'
      fullPath: '/bulkemailsender/campaigns/'
      preLoaderRoute: typeof BulkemailsenderAuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof BulkemailsenderAuthenticatedRouteRoute
    }
    '/bulkemailsender/_authenticated/campaigns/$campaignId': {
      id: '/bulkemailsender/_authenticated/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/bulkemailsender/campaigns/$campaignId'
      preLoaderRoute: typeof BulkemailsenderAuthenticatedCampaignsCampaignIdRouteImport
      parentRoute: typeof BulkemailsenderAuthenticatedRouteRoute
    }
    '/bulkemailsender/_authenticated/campaigns/new': {
      id: '/bulkemailsender/_authenticated/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/bulkemailsender/campaigns/new'
      preLoaderRoute: typeof BulkemailsenderAuthenticatedCampaignsNewRouteImport
      parentRoute: typeof BulkemailsenderAuthenticatedRouteRoute
    }
    '/bulkemailsender/_authenticated/prospects/': {
      id: '/bulkemailsender/_authenticated/prospects/'
      path: '/prospects'
      fullPath: '/bulkemailsender/prospects/'
      preLoaderRoute: typeof BulkemailsenderAuthenticatedProspectsIndexRouteImport
      parentRoute: typeof BulkemailsenderAuthenticatedRouteRoute
    }
    '/bulkemailsender/_authenticated/prospects/$prospectId': {
      id: '/bulkemailsender/_authenticated/prospects/$prospectId'
      path: '/prospects/$prospectId'
      fullPath: '/bulkemailsender/prospects/$prospectId'
      preLoaderRoute: typeof BulkemailsenderAuthenticatedProspectsProspectIdRouteImport
      parentRoute: typeof BulkemailsenderAuthenticatedRouteRoute
    }
    '/bulkemailsender/oauth/google-mail/return': {
      id: '/bulkemailsender/oauth/google-mail/return'
      path: '/oauth/google-mail/return'
      fullPath: '/bulkemailsender/oauth/google-mail/return'
      preLoaderRoute: typeof BulkemailsenderOauthGoogleMailReturnRouteImport
      parentRoute: typeof BulkemailsenderRouteRoute
    }
  }
}

interface BulkemailsenderAuthenticatedRouteRouteChildren {
  BulkemailsenderAuthenticatedAccountsRoute: typeof BulkemailsenderAuthenticatedAccountsRoute
  BulkemailsenderAuthenticatedActivityRoute: typeof BulkemailsenderAuthenticatedActivityRoute
  BulkemailsenderAuthenticatedAnalyticsRoute: typeof BulkemailsenderAuthenticatedAnalyticsRoute
  BulkemailsenderAuthenticatedFollowUpsRoute: typeof BulkemailsenderAuthenticatedFollowUpsRoute
  BulkemailsenderAuthenticatedImportRoute: typeof BulkemailsenderAuthenticatedImportRoute
  BulkemailsenderAuthenticatedSettingsRoute: typeof BulkemailsenderAuthenticatedSettingsRoute
  BulkemailsenderAuthenticatedTemplatesRoute: typeof BulkemailsenderAuthenticatedTemplatesRoute
  BulkemailsenderAuthenticatedIndexRoute: typeof BulkemailsenderAuthenticatedIndexRoute
  BulkemailsenderAuthenticatedCampaignsCampaignIdRoute: typeof BulkemailsenderAuthenticatedCampaignsCampaignIdRoute
  BulkemailsenderAuthenticatedCampaignsNewRoute: typeof BulkemailsenderAuthenticatedCampaignsNewRoute
  BulkemailsenderAuthenticatedProspectsProspectIdRoute: typeof BulkemailsenderAuthenticatedProspectsProspectIdRoute
  BulkemailsenderAuthenticatedCampaignsIndexRoute: typeof BulkemailsenderAuthenticatedCampaignsIndexRoute
  BulkemailsenderAuthenticatedProspectsIndexRoute: typeof BulkemailsenderAuthenticatedProspectsIndexRoute
}

const BulkemailsenderAuthenticatedRouteRouteChildren: BulkemailsenderAuthenticatedRouteRouteChildren =
  {
    BulkemailsenderAuthenticatedAccountsRoute:
      BulkemailsenderAuthenticatedAccountsRoute,
    BulkemailsenderAuthenticatedActivityRoute:
      BulkemailsenderAuthenticatedActivityRoute,
    BulkemailsenderAuthenticatedAnalyticsRoute:
      BulkemailsenderAuthenticatedAnalyticsRoute,
    BulkemailsenderAuthenticatedFollowUpsRoute:
      BulkemailsenderAuthenticatedFollowUpsRoute,
    BulkemailsenderAuthenticatedImportRoute:
      BulkemailsenderAuthenticatedImportRoute,
    BulkemailsenderAuthenticatedSettingsRoute:
      BulkemailsenderAuthenticatedSettingsRoute,
    BulkemailsenderAuthenticatedTemplatesRoute:
      BulkemailsenderAuthenticatedTemplatesRoute,
    BulkemailsenderAuthenticatedIndexRoute:
      BulkemailsenderAuthenticatedIndexRoute,
    BulkemailsenderAuthenticatedCampaignsCampaignIdRoute:
      BulkemailsenderAuthenticatedCampaignsCampaignIdRoute,
    BulkemailsenderAuthenticatedCampaignsNewRoute:
      BulkemailsenderAuthenticatedCampaignsNewRoute,
    BulkemailsenderAuthenticatedProspectsProspectIdRoute:
      BulkemailsenderAuthenticatedProspectsProspectIdRoute,
    BulkemailsenderAuthenticatedCampaignsIndexRoute:
      BulkemailsenderAuthenticatedCampaignsIndexRoute,
    BulkemailsenderAuthenticatedProspectsIndexRoute:
      BulkemailsenderAuthenticatedProspectsIndexRoute,
  }

const BulkemailsenderAuthenticatedRouteRouteWithChildren =
  BulkemailsenderAuthenticatedRouteRoute._addFileChildren(
    BulkemailsenderAuthenticatedRouteRouteChildren,
  )

interface BulkemailsenderRouteRouteChildren {
  BulkemailsenderAuthenticatedRouteRoute: typeof BulkemailsenderAuthenticatedRouteRouteWithChildren
  BulkemailsenderAuthRoute: typeof BulkemailsenderAuthRoute
  BulkemailsenderOauthGoogleMailReturnRoute: typeof BulkemailsenderOauthGoogleMailReturnRoute
}

const BulkemailsenderRouteRouteChildren: BulkemailsenderRouteRouteChildren = {
  BulkemailsenderAuthenticatedRouteRoute:
    BulkemailsenderAuthenticatedRouteRouteWithChildren,
  BulkemailsenderAuthRoute: BulkemailsenderAuthRoute,
  BulkemailsenderOauthGoogleMailReturnRoute:
    BulkemailsenderOauthGoogleMailReturnRoute,
}

const BulkemailsenderRouteRouteWithChildren =
  BulkemailsenderRouteRoute._addFileChildren(BulkemailsenderRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BulkemailsenderRouteRoute: BulkemailsenderRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  BulkemailsenderUnlockRoute: BulkemailsenderUnlockRoute,
  ApiPublicOpenRecipientIdRoute: ApiPublicOpenRecipientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
